# Generated by Django 4.2.7 on 2023-11-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_order_status_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
    ]
