# Generated by Django 4.2.6 on 2023-11-03 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_alter_myuser_date_joined_alter_myuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='pin_code',
            field=models.CharField(default='', max_length=6, verbose_name='pincode'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 24, 1, 437528)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 24, 1, 437528)),
        ),
    ]
