# Generated by Django 4.2.6 on 2023-11-03 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_alter_addresses_pin_code_alter_myuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 27, 34, 972100)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 27, 34, 972100)),
        ),
    ]
