# Generated by Django 4.2.6 on 2023-11-03 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_alter_myuser_date_joined_alter_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='place',
            field=models.CharField(default='place..', max_length=100),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='pin_code',
            field=models.CharField(max_length=6, verbose_name='pincode'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 44, 44, 193771)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 44, 44, 193771)),
        ),
    ]
