# Generated by Django 4.2.6 on 2023-11-03 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_addresses_place_alter_addresses_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 45, 16, 314511)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 45, 16, 314511)),
        ),
    ]
