# Generated by Django 4.2.4 on 2023-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, unique=True)),
                ('cat_img', models.ImageField(blank=True, null=True, upload_to='cat_img')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
