# Generated by Django 4.2.4 on 2023-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_alter_category_options_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discrption',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
